# Generated by Django 3.1 on 2020-08-15 04:21

from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(market.models.MixBase, models.Model),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('meat', 'Meat'), ('fruit', 'Fruit'), ('vegetable', 'Vegatable'), ('desert', 'Desert'), ('dairy', 'Dairy'), ('beverage', 'Beverage'), ('bread', 'Bread')], max_length=11)),
            ],
            bases=(market.models.MixBase, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('n', 'New'), ('s', 'Send'), ('r', 'Received'), ('c', 'Cancelled')], max_length=1)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.cart')),
            ],
            bases=(market.models.MixBase, models.Model),
        ),
        migrations.CreateModel(
            name='CartRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_rows', to='market.cart')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_foods', to='market.food')),
            ],
            bases=(market.models.MixBase, models.Model),
        ),
        migrations.AddField(
            model_name='cart',
            name='rows',
            field=models.ManyToManyField(related_name='carts', through='market.CartRow', to='market.Food'),
        ),
    ]
