# Generated by Django 3.1 on 2020-08-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',)},
        ),
    ]
