# Generated by Django 3.1 on 2020-08-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200816_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartrow',
            options={},
        ),
        migrations.RemoveField(
            model_name='cartrow',
            name='food_order',
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Unit price'),
        ),
    ]
