# Generated by Django 3.1 on 2020-08-15 15:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
