# Generated by Django 3.1 on 2020-08-15 15:34

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200815_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartrow',
            options={'ordering': ['food_order']},
        ),
        migrations.AddField(
            model_name='cartrow',
            name='food_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='food',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_foods', to='market.food'),
        ),
    ]
